export const USER_LOGIN = 'USER_LOGIN';
export const ADD_CURRENCY_KEYS = 'ADD_CURRENCY_KEYS';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REQUEST_QUOTE_CURRENCY = 'REQUEST_QUOTE_CURRENCY';
export const RESPONSE_QUOTE_CURRENCY_SUCCESS = 'RESPONSE_QUOTE_CURRENCY_SUCCESS';
export const RESPONSE_QUOTE_CURRENCY_FAILUTE = 'RESPONSE_QUOTE_CURRENCY_FAILUTE';
